title: "TRIBUS-Directorio de Comercios Locales"
description: "Imaginatorio Cooperative y TRIBUS Actuales GT celebran, a
través de la exposición y divulgación, las grandes ideas que escriben el futuro de Guatemala"
url: "https://directorio-tribus.netlify.app/"
locale: "es_US"
include: ["_redirects"]
image_url: "{{ site.url }}/assets/img/og-image.jpg"
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing. 
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
