title: "TRIBUS-Directorio de Comercios Locales"
description: "Imaginatorio Cooperative y TRIBUS Actuales GT celebran, a
través de la exposición y divulgación, las grandes ideas que escriben el futuro de Guatemala"
url: ""
locale: "es_US"
include: ["_redirects"]
image_url: "{{ site.url }}/assets/img/og-image.jpg"
# Build settings
plugins:
  - jekyll-feed
